swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Terminal test with RESTful API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /command:
    get:
      operationId: command.read
      tags:
        - command
      summary: Read command history
      description: Read command history
      responses:
        200:
          description: Successfully read command history
          schema:
            type: array
            items:
              properties:
                command:
                  type: string
                output:
                  type: string
                timestamp:
                  type: string

    post:
      operationId: command.run
      tags:
        - command
      summary: Run the given command
      description: Run the given command
      parameters:
        - name: command
          in: body
          description: Command to run
          required: True
          schema:
            type: object
            properties:
              command:
                type: string
                description: Command to run
      responses:
        200:
          description: Successfully ran command